# Generated by Django 3.2.6 on 2021-08-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210811_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
