# Generated by Django 3.2.6 on 2021-08-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_software_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ram_total',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='software_ver',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
