# Generated by Django 3.2.6 on 2021-08-13 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
