# Generated by Django 3.2.6 on 2021-08-12 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='num',
            new_name='proj_num',
        ),
        migrations.AddField(
            model_name='device',
            name='ram_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
